Feature: Disable feature to test Cache functionality manually 
#   This test can work only against one worker with clean cache (in OSS container puma is running with 2 workers),
#   since the cache is saved in worker context and not in the whole cluster,
#   Note: run the following test manually with the command 'puma --workers 0'
  
  Background:
    Given a policy:
    """
    - !policy
      id: conjur/authn-oidc/keycloak
      body:
      - !webservice
        annotations:
          description: Authentication service for Keycloak, based on Open ID Connect.

      - !variable
        id: provider-uri

      - !variable
        id: id-token-user-property

      - !group users

      - !permit
        role: !group users
        privilege: [ read, authenticate ]
        resource: !webservice

    - !user alice

    - !grant
      role: !group conjur/authn-oidc/keycloak/users
      member: !user alice
    """
    And I am the super-user
    And I successfully set OIDC variables
    
  Scenario: Cache - Exceed refreshes_per_interval
    # Validate we have certificate in the cache
    Given I get authorization code for username "alice" and password "alice"
    And I fetch an ID Token
    And I authenticate via OIDC with id token
    And user "alice" is authorized
    And I save my place in the log file
    # Running 3 threads at a time so we don't exceed the concurrency limit
    When I authenticate "3" times in "3" threads via OIDC with invalid id token
    When I authenticate "3" times in "3" threads via OIDC with invalid id token
    When I authenticate "3" times in "3" threads via OIDC with invalid id token
    When I authenticate "1" times in "1" threads via OIDC with invalid id token
    # ID Token decoding should fail 2 times per call - one before refreshing certs and one after
    Then The following appears in the log after my savepoint:
    """
    CONJ00018D Failed to decode the ID Token with the error
    """
    # Rate limited cache should be updated "refreshes_per_interval"-1 times
    And The following appears in the log after my savepoint:
    """
    CONJ00016D Rate limited cache updated successfully
    """
    When I save my place in the log file
    And I authenticate "3" times in "3" threads via OIDC with invalid id token
    # We log that the limit has been reached per request
    Then The following appears "3" times in the log after my savepoint:
    """
    CONJ00020D Rate limited cache reached
    """
    # Rate limited cache should not be updated after limit is reached
    And The following appears "0" times in the log after my savepoint:
    """
    CONJ00016D Rate limited cache updated successfully
    """
    When I save my place in the log file
    And I get authorization code for username "alice" and password "alice"
    And I fetch an ID Token
    And I authenticate via OIDC with id token
    Then user "alice" is authorized
    And The following appears "1" times in the log after my savepoint:
    """
    CONJ00017D OIDC Provider certificates fetched successfully from cache
    """

  Scenario: Cache - Exceed refreshes_per_interval , cache not initialized
    # TODO: start the server to have a clean cache
    Given I get authorization code for username "alice" and password "alice"
    And I fetch an ID Token
    And I authenticate via OIDC with id token
    And I save my place in the log file
    # Running 10 threads at a time so we surely exceed the 3 concurrency limit
    When I authenticate "10" times in "10" threads via OIDC with invalid id token
    Then The following appears in the log after my savepoint:
    """
    CONJ00044E Concurrency limited cache reached before cache initialized
    """
    And The following appears in the log after my savepoint:
    """
    503 Service Unavailable
    """

  Scenario: Load unreachable provider-uri requests
    # I have a valid certificate in the cache
    Given I get authorization code for username "alice" and password "alice"
    And I fetch an ID Token
    And I authenticate via OIDC with id token
    And user "alice" is authorized
    # load of invalid requests above the "refreshes_per_interval"
    When I add the secret value "http://unreachable.com/" to the resource "cucumber:variable:conjur/authn-oidc/keycloak/provider-uri"
    And I save my place in the log file
    And I authenticate "20" times in "20" threads via OIDC with id token
    Then The following appears in the log after my savepoint:
    """
    CONJ00022D Concurrency limited cache reached
    """
    # The server is available (the multiple timeouts errors blocked by concurrency cache limit)
    And I authenticate as "alice" with account "cucumber"
    And the HTTP response status code is 200
